FROM node:16.17.0
WORKDIR /web
COPY ./web ./
RUN npm install
EXPOSE 5173
CMD ["npm","run","dev"]

FROM python:3.10.10
WORKDIR /backend
COPY ./backend ./
RUN pip install -r requirements.txt
EXPOSE 8001
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8001"]