FROM node:16.17.0 as frontend-builder
WORKDIR /opt/app
COPY ./web ./
RUN npm install
ENV NODE_ENV=development
RUN npm run build

FROM python:3.10.10 as backend-builder
WORKDIR /backend
COPY ./backend ./
RUN pip install -r requirements.txt

WORKDIR /opt/app
COPY --from=frontend-builder /opt/app/dist/ ./static/
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","8000"]

EXPOSE 8000