export type CSItem = {
  itemid: string;
  defindex: number;
  paintindex: number;
  rarity: number;
  quality: number;
  paintseed: number;
  killeatervalue: number;
  customname: string;
  stickers: Array<any> | null;
  origin: number;
  floatvalue: number;
  imageurl: string;
  min: number;
  max: number;
  item_name: number;
  weapon_type: string;
  origin_name: string;
  quality_name: string;
  rarity_name: string;
  wear_name: string;
  full_item_name: string;
};
